// Generated by CoffeeScript 1.3.3
var BaseError, EOFError,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseError = (function(_super) {

  __extends(BaseError, _super);

  function BaseError(msg) {
    Error.captureStackTrace(this, this.constructor);
    this.name = this.constructor.name;
    this.message = msg;
    BaseError.__super__.constructor.apply(this, arguments);
  }

  return BaseError;

})(Error);

EOFError = (function(_super) {

  __extends(EOFError, _super);

  function EOFError() {
    return EOFError.__super__.constructor.apply(this, arguments);
  }

  return EOFError;

})(BaseError);

module.exports = {
  BaseError: BaseError,
  EOFError: EOFError
};
