// Generated by CoffeeScript 1.6.3
var BaseError, EOFError, NotImplementedError, UnicodeDecodeError, ValueError, _ref, _ref1, _ref2, _ref3,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseError = (function(_super) {
  __extends(BaseError, _super);

  function BaseError(msg) {
    Error.captureStackTrace(this, this.constructor);
    this.name = this.constructor.name;
    this.message = msg;
    BaseError.__super__.constructor.apply(this, arguments);
  }

  return BaseError;

})(Error);

EOFError = (function(_super) {
  __extends(EOFError, _super);

  function EOFError() {
    _ref = EOFError.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return EOFError;

})(BaseError);

NotImplementedError = (function(_super) {
  __extends(NotImplementedError, _super);

  function NotImplementedError() {
    _ref1 = NotImplementedError.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  return NotImplementedError;

})(BaseError);

ValueError = (function(_super) {
  __extends(ValueError, _super);

  function ValueError() {
    _ref2 = ValueError.__super__.constructor.apply(this, arguments);
    return _ref2;
  }

  return ValueError;

})(BaseError);

UnicodeDecodeError = (function(_super) {
  __extends(UnicodeDecodeError, _super);

  function UnicodeDecodeError() {
    _ref3 = UnicodeDecodeError.__super__.constructor.apply(this, arguments);
    return _ref3;
  }

  return UnicodeDecodeError;

})(ValueError);

module.exports = {
  BaseError: BaseError,
  EOFError: EOFError,
  NotImplementedError: NotImplementedError,
  ValueError: ValueError,
  UnicodeDecodeError: UnicodeDecodeError
};
