// Generated by CoffeeScript 1.3.3
var BaseError, BitPaddedInt, EOFError, Frame, ID3, ID3NoHeaderError, ID3UnsupportedVersionError, ParseID3v1, convert, fs, sprintf, unsynch, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

fs = require('fs');

_ = require('underscore');

sprintf = require("sprintf-js").sprintf;

convert = require('./text-encodings');

unsynch = require('./unsynch');

BitPaddedInt = require('./BitPaddedInt');

Frame = require('./Frame');

BaseError = require('./errors.js').BaseError;

EOFError = require('./errors.js').EOFError;

ID3NoHeaderError = (function(_super) {

  __extends(ID3NoHeaderError, _super);

  function ID3NoHeaderError() {
    return ID3NoHeaderError.__super__.constructor.apply(this, arguments);
  }

  return ID3NoHeaderError;

})(BaseError);

ID3UnsupportedVersionError = (function(_super) {

  __extends(ID3UnsupportedVersionError, _super);

  function ID3UnsupportedVersionError() {
    return ID3UnsupportedVersionError.__super__.constructor.apply(this, arguments);
  }

  return ID3UnsupportedVersionError;

})(BaseError);

ID3 = (function() {

  function ID3(filepath) {
    this.__readbytes = 0;
    this.unknownFrames = [];
    this.__flags = 0;
    this.version = {
      major: 2,
      minor: 4,
      sub: 0
    };
    Object.defineProperty(this, 'f_unsynch', {
      enumerable: true,
      get: function() {
        return (this.__flags & 0x80) !== 0;
      }
    });
    Object.defineProperty(this, 'f_extended', {
      enumerable: true,
      get: function() {
        return (this.__flags & 0x40) !== 0;
      }
    });
    Object.defineProperty(this, 'f_experimental', {
      enumerable: true,
      get: function() {
        return (this.__flags & 0x20) !== 0;
      }
    });
    Object.defineProperty(this, 'f_footer', {
      enumerable: true,
      get: function() {
        return (this.__flags & 0x10) !== 0;
      }
    });
    if (filepath != null) {
      this.load(filepath);
    }
  }

  ID3.prototype.fullRead = function(size) {
    var buff, bytesRead;
    if (size < 0) {
      throw new Error("Requested bytes " + size + " less than zero");
    }
    if (size > this.__filesize) {
      throw new EOFError("Requested " + size + " of " + this.__filesize + " " + this.filepath);
    }
    buff = new Buffer(size);
    bytesRead = fs.readSync(this.__fileobj, buff, 0, size, this.__readbytes);
    if (bytesRead !== size) {
      throw new EOFError('End of file');
    }
    this.__readbytes += bytesRead;
    return buff;
  };

  ID3.prototype.load = function(filepath) {
    var data, frame, frames, headerLoaded, name, readFrame, _results;
    this.filepath = filepath;
    this.__fileobj = fs.openSync(filepath, 'r');
    this.__filesize = fs.statSync(filepath).size;
    try {
      headerLoaded = false;
      try {
        this.loadHeader();
        return headerLoaded = true;
      } catch (err) {
        if (err instanceof EOFError) {
          this.size = 0;
          throw new ID3NoHeaderError("" + this.filepath + ": too small (" + this.__filesize + " bytes)");
        } else if (err instanceof ID3NoHeaderError || err instanceof ID3UnsupportedVersionError) {
          this.size = 0;
          if (this.__filesize >= 128) {
            this.__readbytes = this.__filesize - 128;
            frames = ParseID3v1(this.fullRead(128));
            if (frames) {
              this.version = {
                major: 1,
                minor: 1
              };
              _results = [];
              for (name in frames) {
                frame = frames[name];
                _results.push(this.add(frame));
              }
              return _results;
            } else {
              throw err;
            }
          } else {
            throw err;
          }
        }
      } finally {
        if (headerLoaded) {
          if (this.version.minor >= 3) {
            frames = Frame.FRAMES;
          } else if (this.version.minor <= 2) {
            frames = Frame.FRAMES_2_2;
          }
          data = this.fullRead(this.size - 10);
          readFrame = this.getFrameReader(data, frames);
          frame = false;
          while ((frame = readFrame()) !== false) {
            if (frame instanceof Frame) {
              this.add(frame);
            } else if (frame != null) {
              this.unknownFrames.push(frame);
            }
          }
        }
      }
    } finally {
      fs.closeSync(this.__fileobj);
      this.__fileobj = null;
      this.__filesize = null;
    }
  };

  ID3.prototype.add = function(frame) {
    return this[frame.HashKey] = frame;
  };

  ID3.prototype.loadHeader = function() {
    var data, extSizeRepr, id3, offset, sizeRepr, _ref;
    data = this.fullRead(10);
    offset = 0;
    id3 = (convert(data.slice(offset, offset += 3))).from('latin1');
    this.version = {
      major: 2,
      minor: data.readUInt8(offset++),
      sub: data.readUInt8(offset++)
    };
    this.__flags = data.readUInt8(offset++);
    sizeRepr = (convert(data.slice(offset, offset += 4))).from('latin1');
    this.size = BitPaddedInt(sizeRepr) + 10;
    if (id3 !== 'ID3') {
      throw new ID3NoHeaderError("" + this.filepath + " doesn't start with an ID3 tag");
    }
    if ((_ref = this.version.minor) !== 2 && _ref !== 3 && _ref !== 4) {
      throw new ID3UnsupportedVersionError("" + this.filepath + " ID3v2." + this.version.minor + " not supported");
    }
    if (this.f_extended) {
      data = this.fullRead(4);
      extSizeRepr = (convert(data)).from('latin1');
      if (Frame.FRAMES[extSizeRepr]) {
        this.__flags = this.__flags ^ 0x40;
        this.__extsize = 0;
        this.__readbytes -= 4;
      } else if (this.version.minor >= 4) {
        this.__extsize = BitPaddedInt(extSizeRepr) - 4;
      } else {
        this.__extsize = BitPaddedInt(extSizeRepr, 8);
      }
      this.__extdata = '';
      if (this.__extsize) {
        data = this.fullRead(this.__extsize);
        return this.__extdata = data.toString('hex');
      }
    }
  };

  ID3.prototype.getFrameReader = function(data, frames) {
    var bpi, reader,
      _this = this;
    if ((this.version.minor < 4) && this.f_unsynch) {
      try {
        data = unsynch.decode(data);
      } catch (err) {

      }
    }
    if (3 <= this.version.minor) {
      bpi = this.determineBPI(data, frames);
      return reader = function() {
        var flags, framedata, header, name, offset, size, tag;
        while (true) {
          try {
            header = data.slice(0, 10);
            offset = 0;
            name = (convert(header.slice(offset, offset += 4))).from('latin1');
            size = header.readUInt32BE(offset);
            offset += 4;
            flags = header.readUInt16BE(offset);
          } catch (err) {
            console.log(_this.filepath);
            console.log(err.stack, '\n');
            return false;
          }
          if ((name.replace(/[\x00]+$/g, '')) === '') {
            return false;
          }
          size = bpi(size);
          framedata = data.slice(10, 10 + size);
          data = data.slice(10 + size);
          if (!(size === 0)) {
            break;
          }
        }
        tag = frames[name];
        if (tag === void 0 || typeof tag === 'string') {
          if (Frame.isValidFrameId(name)) {
            return header + framedata;
          }
        } else {
          try {
            return _this.loadFramedata(tag, flags, framedata);
          } catch (err) {
            console.log(_this.filepath);
            return console.log(err.stack, '\n');
          }
        }
      };
    } else if (2 <= this.version.minor) {
      return reader = function() {
        var framedata, header, name, offset, size, tag;
        while (true) {
          try {
            header = data.slice(0, 6);
            offset = 0;
            name = (convert(header.slice(offset, offset += 3))).from('latin1');
            size = header.slice(offset, offset += 3);
          } catch (err) {
            console.log(_this.filepath);
            console.log(err.stack, '\n');
            return false;
          }
          size = Buffer.concat([new Buffer('00', 'hex'), size]);
          size = size.readUInt32BE(0);
          if ((name.replace(/[\x00]+$/g, '')) === '') {
            return false;
          }
          framedata = data.slice(6, 6 + size);
          data = data.slice(6 + size);
          if (!(size === 0)) {
            break;
          }
        }
        tag = frames[name];
        if (tag === void 0 || typeof tag === 'string') {
          if (Frame.isValidFrameId(name)) {
            return header + framedata;
          }
        } else {
          try {
            return _this.loadFramedata(tag, 0, framedata);
          } catch (err) {
            console.log(_this.filepath);
            return console.log(err.stack, '\n');
          }
        }
      };
    }
  };

  ID3.prototype.loadFramedata = function(tag, flags, data) {
    return tag.fromData(tag, this, flags, data);
  };

  ID3.prototype.determineBPI = function(data, frames) {
    var EMPTY, asbpi, asint, bpioff, flags, intoff, name, o, part, size;
    EMPTY = "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00";
    if (this.version.minor < 4) {
      return function(i) {
        return parseInt(i, 10);
      };
    }
    o = 0;
    asbpi = 0;
    while (o < (data.length - 10)) {
      part = data.slice(o, o + 10);
      if (part === EMPTY) {
        bpioff = -((data.length - o) % 10);
        break;
      }
      name = (convert(part.slice(0, 4))).from('latin1');
      size = part.readUInt32BE(4);
      flags = part.readUInt16BE(8);
      size = BitPaddedInt(size);
      o += 10 + size;
      if (frames[name] != null) {
        asbpi++;
      }
      if (!o < (data.length - 10)) {
        bpioff = o - data.length;
      }
    }
    o = 0;
    asint = 0;
    while (o < (data.length - 10)) {
      part = data.slice(o, o + 10);
      if (part === EMPTY) {
        intoff = -((data.length - o) % 10);
        break;
      }
      name = (convert(part.slice(0, 4))).from('latin1');
      size = part.readUInt32BE(4);
      flags = part.readUInt16BE(8);
      o += 10 + size;
      if (frames[name] != null) {
        asint++;
      }
      if (!o < (data.length - 10)) {
        intoff = o - data.length;
      }
    }
    if ((asint > asbpi) || ((asint === asbpi) && ((bpioff >= 1) && (intoff <= 1)))) {
      return function(i) {
        return parseInt(i, 10);
      };
    }
    return function(i) {
      return BitPaddedInt(i);
    };
  };

  return ID3;

})();

module.exports = ID3;

ParseID3v1 = function(buffer) {
  var album, artist, comment, fix, frames, genre, hexString, offset, str, tag, tagByteLength, title, track, year, _ref;
  hexString = buffer.toString('hex');
  hexString = hexString.slice(hexString.indexOf('544147'));
  if (hexString === -1) {
    return null;
  }
  tagByteLength = Buffer.byteLength(hexString, 'hex');
  if (128 < tagByteLength || tagByteLength < 124) {
    return null;
  }
  buffer = new Buffer(hexString, 'hex');
  try {
    offset = 0;
    tag = (convert(buffer.slice(offset, offset += 3))).from('latin1');
    title = (convert(buffer.slice(offset, offset += 30))).from('latin1');
    artist = (convert(buffer.slice(offset, offset += 30))).from('latin1');
    album = (convert(buffer.slice(offset, offset += 30))).from('latin1');
    year = (convert(buffer.slice(offset, offset += tagByteLength - 124))).from('latin1');
    comment = (convert(buffer.slice(offset, offset += 29))).from('latin1');
    track = buffer.readUInt8(offset++);
    genre = buffer.readUInt8(offset++);
  } catch (err) {
    return null;
  }
  if (tag !== 'TAG') {
    return null;
  }
  fix = function(string) {
    return string.split('\u0000')[0].trim();
  };
  _ref = (function() {
    var _i, _len, _ref, _results;
    _ref = [title, artist, album, year, comment];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      str = _ref[_i];
      _results.push(fix(str));
    }
    return _results;
  })(), title = _ref[0], artist = _ref[1], album = _ref[2], year = _ref[3], comment = _ref[4];
  frames = {};
  if (title) {
    frames["TIT2"] = new Frame.FRAMES.TIT2({
      encoding: 0,
      text: title
    });
  }
  if (artist) {
    frames["TPE1"] = new Frame.FRAMES.TPE1({
      encoding: 0,
      text: [artist]
    });
  }
  if (album) {
    frames["TALB"] = new Frame.FRAMES.TALB({
      encoding: 0,
      text: album
    });
  }
  if (year) {
    frames["TDRC"] = new Frame.FRAMES.TDRC({
      encoding: 0,
      text: year
    });
  }
  if (comment) {
    frames["COMM"] = new Frame.FRAMES.COMM({
      encoding: 0,
      lang: "eng",
      desc: "ID3v1 Comment",
      text: comment
    });
  }
  if (track && (track !== 32 || hexString.slice(-6, -4) === '00')) {
    frames["TRCK"] = new Frame.FRAMES.TRCK({
      encoding: 0,
      text: track.toString()
    });
  }
  return frames;
};
