// Generated by CoffeeScript 1.6.3
var ID3, Metatag;

ID3 = require('./id3');

Metatag = (function() {
  function Metatag(filepath) {
    return new ID3(filepath);
  }

  return Metatag;

})();

module.exports = Metatag;
