// Generated by CoffeeScript 1.6.3
var ID3, Metatag;

ID3 = require('./id3');

Metatag = (function() {
  function Metatag(filepath, callback) {
    return (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args);
      return Object(result) === result ? result : child;
    })(ID3, arguments, function(){});
  }

  return Metatag;

})();

module.exports = Metatag;
