// Generated by CoffeeScript 1.3.3
var unsynch;

unsynch = {
  decode: function(buffer) {
    var couplet, first, hexVal, idx, output, safe, _i, _len, _step;
    hexVal = buffer.toString('hex');
    output = [];
    safe = true;
    for (idx = _i = 0, _len = hexVal.length, _step = 2; _i < _len; idx = _i += _step) {
      first = hexVal[idx];
      couplet = first + hexVal[idx + 1];
      if (safe) {
        output.push(couplet);
        safe = couplet !== 'ff';
      } else {
        if (couplet >= 'e0') {
          throw new Error('invalid sync-safe string');
        } else if (couplet !== '00') {
          output.push(couplet);
        }
        safe = true;
      }
    }
    if (!safe) {
      throw new Error('string ended unsafe');
    }
    return new Buffer(output.join(''), 'hex');
  }
};

module.exports = unsynch;
