// Generated by CoffeeScript 1.6.3
var BaseError, ID3NoHeaderError, ID3UnsupportedVersionError, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseError = require('../errors').BaseError;

ID3NoHeaderError = (function(_super) {
  __extends(ID3NoHeaderError, _super);

  function ID3NoHeaderError() {
    _ref = ID3NoHeaderError.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return ID3NoHeaderError;

})(BaseError);

ID3UnsupportedVersionError = (function(_super) {
  __extends(ID3UnsupportedVersionError, _super);

  function ID3UnsupportedVersionError() {
    _ref1 = ID3UnsupportedVersionError.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  return ID3UnsupportedVersionError;

})(BaseError);

module.exports = {
  ID3NoHeaderError: ID3NoHeaderError,
  ID3UnsupportedVersionError: ID3UnsupportedVersionError
};
