// Generated by CoffeeScript 1.6.3
var ID3BadUnsynchData, ID3EncyptionUnsupportedError, ID3JunkFrameError, ID3NoHeaderError, ID3UnsupportedVersionError, NotImplementedError, ValueError, _ref, _ref1, _ref2, _ref3, _ref4, _ref5,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ref = require('../errors'), ValueError = _ref.ValueError, NotImplementedError = _ref.NotImplementedError;

ID3NoHeaderError = (function(_super) {
  __extends(ID3NoHeaderError, _super);

  function ID3NoHeaderError() {
    _ref1 = ID3NoHeaderError.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  return ID3NoHeaderError;

})(ValueError);

ID3BadUnsynchData = (function(_super) {
  __extends(ID3BadUnsynchData, _super);

  function ID3BadUnsynchData() {
    _ref2 = ID3BadUnsynchData.__super__.constructor.apply(this, arguments);
    return _ref2;
  }

  return ID3BadUnsynchData;

})(ValueError);

ID3UnsupportedVersionError = (function(_super) {
  __extends(ID3UnsupportedVersionError, _super);

  function ID3UnsupportedVersionError() {
    _ref3 = ID3UnsupportedVersionError.__super__.constructor.apply(this, arguments);
    return _ref3;
  }

  return ID3UnsupportedVersionError;

})(NotImplementedError);

ID3EncyptionUnsupportedError = (function(_super) {
  __extends(ID3EncyptionUnsupportedError, _super);

  function ID3EncyptionUnsupportedError() {
    _ref4 = ID3EncyptionUnsupportedError.__super__.constructor.apply(this, arguments);
    return _ref4;
  }

  return ID3EncyptionUnsupportedError;

})(NotImplementedError);

ID3JunkFrameError = (function(_super) {
  __extends(ID3JunkFrameError, _super);

  function ID3JunkFrameError() {
    _ref5 = ID3JunkFrameError.__super__.constructor.apply(this, arguments);
    return _ref5;
  }

  return ID3JunkFrameError;

})(ValueError);

module.exports = {
  ID3NoHeaderError: ID3NoHeaderError,
  ID3BadUnsynchData: ID3BadUnsynchData,
  ID3UnsupportedVersionError: ID3UnsupportedVersionError,
  ID3EncyptionUnsupportedError: ID3EncyptionUnsupportedError,
  ID3JunkFrameError: ID3JunkFrameError
};
