// Generated by CoffeeScript 1.6.3
var ValueError, unsynch;

ValueError = require('../errors').ValueError;

unsynch = {
  decode: function(buffer) {
    var couplet, first, hexVal, idx, output, safe, _i, _len;
    hexVal = buffer.toString('hex');
    output = [];
    safe = true;
    for (idx = _i = 0, _len = hexVal.length; _i < _len; idx = _i += 2) {
      first = hexVal[idx];
      couplet = first + hexVal[idx + 1];
      if (safe) {
        output.push(couplet);
        safe = couplet !== 'ff';
      } else {
        if (couplet >= 'e0') {
          throw new ValueError('invalid sync-safe string');
        } else if (couplet !== '00') {
          output.push(couplet);
        }
        safe = true;
      }
    }
    if (!safe) {
      throw new ValueError('string ended unsafe');
    }
    return new Buffer(output.join(''), 'hex');
  }
};

module.exports = unsynch;
